version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: svg-sprite-loader
    versions:
    - 5.2.1
    - 6.0.0
    - 6.0.2
    - 6.0.5
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: svgo-loader
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: react-popper
    versions:
    - 1.3.10
    - 1.3.7
    - 1.3.8
    - 1.3.9
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
    - 11.0.3
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: react-modal
    versions:
    - 3.12.1
  - dependency-name: react-error-overlay
    versions:
    - 6.0.8
  - dependency-name: sass-resources-loader
    versions:
    - 2.1.1
  - dependency-name: flow-typed
    versions:
    - 3.2.1
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: cssnano
    versions:
    - 4.1.10
  - dependency-name: case-sensitive-paths-webpack-plugin
    versions:
    - 2.3.0
  - dependency-name: urijs
    versions:
    - 1.19.5
